services:
  api:
    build: ./api
    restart: unless-stopped
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
        interval: 5s
        timeout: 5s
        retries: 10
        start_period: 0s
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - api